### ISSUE TITLE
Webhook for commit-email.info

### ISSUE THREAD

**Issue by kou** [ruby/rss#15]
@hsbt I want to set a webhook for [commit-email.info](https://www.commit-email.info/) to this repository. Could you provide the "Admin" role for this repository to me? Or could you add the following webhook?

* Payload URL: https://webhook.commit-email.info/
* Content type: application/json
* SSL verification: ENable SSL verification
* Events:
  * Check suites
  * Wiki
  * Pushes

**Comment by kou** [comment]
Ah, it already exists...?

**Comment by hsbt** [comment]
Yes, It has been prepared in the current configuration.

I added admin grant to you in this repository. Can you check them?

**Comment by kou** [comment]
Thanks.
I've confirmed.
