### ISSUE TITLE
Anyway to generate content as CDATA?

### ISSUE THREAD

**Issue by ecnelises** [ruby/rss#19]
This is helpful when there're XML/HTML tags inside summary contents. But I did not find a way to achieve it. [A method from StackOverflow](https://stackoverflow.com/questions/24722863) doesn't work now.

Ruby version: ruby 2.7.0p0 (2019-12-25 revision https://github.com/ruby/ruby/commit/647ee6f091)

**Comment by kou** [comment]
Why do you want to use `<![CDATA[...]]>`?
`<![CDATA[...]]>` and escaped text are logically same in XML.

**Comment by ecnelises** [comment]
hmm.. I wrote a script to generate a feed for myself. But it seems my reader only decodes HTML escape characters back but take them as plain text, not HTML/XML tags. While `<![CDATA[...]]>` works.

If they're the same according to spec, there should be some problem with my reader. But at least I can manually add CDATA tag and finally decode it back.. Thanks.

**Comment by kou** [comment]
Could you report this to your reader?
