### ISSUE TITLE
Paged feeds (RFC 5005)?

### ISSUE THREAD

**Issue by suhlig** [ruby/rss#22]
[RFC 5005](https://tools.ietf.org/html/rfc5005) describes paging for (large) Atom and RSS feeds:

> A paged feed is a set of linked feed documents that together contain the entries[...]

Reading the current documentation of `ruby/rss`, it seems not supported currently. Are there plans to add it, or perhaps a willingness to consider a PR?

**Comment by kou** [comment]
We don't support it yet.

We accept a PR to support it.

**Comment by suhlig** [comment]
Thanks.
