### ISSUE TITLE
Trouble setting categories for RSS 2.0 feed

### ISSUE THREAD

**Issue by rgarner** [ruby/rss#29]
Hi! I've had a similar issue to #28 today with trying to set categories on an Rss 2.0 feed. I couldn't set `categories=`, but I appeared to be able to do

```ruby
  item.categories << 'Digital specialists'
```

... but when the feed was generated, I'd get 

```
  NoMethodError:
       undefined method `to_feed' for "Digital specialists":String`
```

Eventually, by some trial and error and a debugger, I found that what I seemingly need to do is

```ruby
  category = RSS::Maker::RSS20::Channel::Categories::Category.new(maker)
  category.content = 'Digital specialists'
  item.categories << category
```

Is there a shorter way of doing this, and is there a way in which I might be able to contribute to the docs to cover both this sort of example and the one from #28?

**Comment by rgarner** [comment]
Ah, ok, found the [tests for this](https://github.com/ruby/rss/blob/master/test/test-maker-2.0.rb#L655-L658) in this repo – I was working from `lib/ruby` and so was guessing!

**Comment by kou** [comment]
Right.
