### ISSUE TITLE
can't parse media:thumbnail

### ISSUE THREAD

**Issue by g13ydson** [ruby/rss#30]
I'm trying to parse an RSS file that has a media thumbnail, but it looks like we don't have support for that yet.

`<media:thumbnail url="http://www.foo.com/keyframe.jpg" width="75" height="50" time="12:05:01.123" />
`

`RSS::Parser.parse('https://justthenews.com/syndication/willcountygazette.com/rss.xml')`

**Comment by kou** [comment]
This can be solved when we solve #18.
