### ISSUE TITLE
Handling missing tags when parsing feeds

### ISSUE THREAD

**Issue by forthrin** [ruby/rss#43]
`RSS::Parser.parse(open('foo.xml'))` on a feed that *lacks* the elements marked `NULL` gives:

`rss-0.2.9/lib/rss/rss.rb:1180:in 'block in _validate': tag <title> is missing in tag <image> (RSS::MissingTagError)`

Is there any way to recover from / ignore this? Or must one switch to XML parsing with Nokogiri?

```
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">
  <channel>
    <link>NULL</link>
    <title></title>
    <description></description>
    <itunes:owner>
      <itunes:name>NULL</itunes:name>
      <itunes:email></itunes:email>
    </itunes:owner>
    <image>
      <link>NULL</link>
      <title></title>
      <url></url>
    </image>
  </channel>
</rss>

```

**Comment by kou** [comment]
I couldn't reproduce the error with the given XML.
Is your XML really has an empty `<title></title>`?

BTW, you can disable the validation by `RSS::Parser.parse(open('foo.xml'), false)`.

**Comment by forthrin** [comment]
No, *lacks* the elements, as in, they are not present at all. The `false` argument should resolve this. Thanks!
