### ISSUE TITLE
Is there any way to access unparsed tags?

### ISSUE THREAD

**Issue by timuckun** [ruby/rss#45]
I have the following code

```ruby
MINDSCAPE_FEED='https://rss.art19.com/sean-carrolls-mindscape'
URI.open(MINDSCAPE_FEED) do |rss|

  feed = RSS::Parser.parse(rss, ignore_unknown_element=true)

  puts "Title: #{feed.channel.title}"
  feed.items.each do |item|
    puts item.itunes_episode_type
  end
end
```

Is there any way to access the itunes::episodeType attribute?  More generically is there a way to access tags that the parser doesn't know about?

**Comment by olleolleolle** [comment]
I learned a little more about `itunes:episodeType` at [Apple's Help Page for their podcast RSS extensions](https://help.apple.com/itc/podcasts_connect/#/itcb54353390).

Not answering your question: but guessing at a solution that changes the ruby/rss implementation!

Perhaps adding `episodeType` to the `item` section of the itunes-specific code in this repo would be a way to get the data? https://github.com/ruby/rss/blob/master/lib/rss/itunes.rb#L267 - I am suggesting that this list of tags could be extended to also know about the `episodeType`?

Hope this helps - and do make a PR if you feel you want to pursue it.

**Comment by timuckun** [comment]
I think that if there was a way to access a tag by name it would be a more generic solution so that the code doesn't have to change every time somebody decides to add a tag to their RSS feed.

Maybe even adding a hook where I could write a couple of lines of code would be OK.

**Comment by kou** [comment]
I've implemented it and released a new version.

We'll not provide accessors for unknown tags. It's by design.
