### ISSUE TITLE
Test failed with ruby/ruby with rexml-3.3.4

### ISSUE THREAD

**Issue by hsbt** [ruby/rss#54]
https://github.com/ruby/ruby/actions/runs/10211279098/job/28252311558#step:13:290

```
  Error: test_parse(RSS::TestParser):
    RSS::NotWellFormedError: This is not well formed XML
    Malformed XML: Content at the start of the document (got '/tmp/rss10-20240802-16264-835wxo.rdf-garbage')
    Line: 1
    Position: 44
    Last 80 unconsumed characters:
```

This test is not failing with my local environment.

**Comment by kou** [comment]
I've fixed it.
I'll release a new version later.

**Comment by hsbt** [comment]
Thanks!

**Comment by kou** [comment]
Released.

**Comment by hsbt** [comment]
rss-0.3.1 resolve that. 

https://github.com/ruby/ruby/commit/657f4b99f61a15e21584b87f7b206933d116589b

Thanks, again.
