### ISSUE TITLE
Cannot parse RSS with new version of rexml

### ISSUE THREAD

**Issue by mawise** [ruby/rss#56]
Hi,

Thanks so much for your work maintaining the `rss` gem!  It is central to the open-source RSS feed reader I build and maintain (https://github.com/havenweb/haven)

I'm using the `rss` gem to parse RSS feeds.  Recently I tried updating the version of `rexml` (which `rss` depends on) and it broke on some of my tests.  This file:

> https://github.com/havenweb/haven/blob/master/test/fixtures/files/haven-rss.xml

Can be parsed by the `rss` gem (version `0.2.9` or `0.3.1`) with `rexml` version `3.3.2` using the following code:

```
rss_content = File.open("haven-rss.xml")
rss_parsed = RSS::Parser.parse(rss_content, validate: false)
```

However, it fails with `rexml` versions `3.3.3`, `3.3.4`, and `3.3.5` with the following error:

```
This is not well formed XML (RSS::NotWellFormedError)
entity expansion has grown too large
```

(I'm using ruby version `3.1.4`)

This is an unfortunate change in behavior.  Is there any chance you would be able to maintain `rss`'s functionality?  I really appreciate your help,

Matt

**Comment by kou** [comment]
Ah, it should be fixed in the next 3.3.6 release.
I'll release it soon.

**Comment by kou** [comment]
Could you try REXML 3.3.6?

**Comment by mawise** [comment]
@kou That works great, Thank you!!
